### PR TITLE
Magnetometer upgrade

### PR DESCRIPTION
**Pull request by jlipschutz**
Hey Cai and Jaden,

I have been working with the BNO005 (magnetometer) and MTK3339 (gps) and its implementation in Scarlet. I have been working on creating a new BNO constructor that takes a MTK as an argument in its constructor so I can get the true heading by getting the magnetic declination determined by the given coordinates from the MTK. To do this I created a branch of Scarlet that makes two changes:

1. Change BNO005.cs such that it can take an MTK as a part of its constructor and added a new getTrueHeading() method.
2. Created a new class in Scarlet.Utilities called DeclinationHelper that runs all the matrix operations necessary to accurately calculate the magnetic declination using the World Magnetic Model coefficients.

I was wondering what steps I should take to submit a pull request for these changes. The branch these changes are under is called MagnetometerUpgrade.

Thanks!

### CODE REVIEW

**Comment by jlipschutz** [comment]
We updated this code such that the BNO055 takes in an IGps interface instead of taking in only an MTK3339.

**Comment by Baldstrom** [comment]
Except for the CodeFactor problems that need to be addressed, I am okay with this. The architecture of this looks okay to me. 👌 
But also, I am a bit confused as to why there are build items in this PR. Did you force add them?

**Comment by jlipschutz** [comment]
I just did git add --all, that probably added the build items. My bad.

**Comment by CaiB** [comment]
Sorry for the long delay in getting this integrated.

Where is the declination calculation data from? Are we allowed to put this into Scarlet, with it being licensed LGPLv3?

**Comment by CaiB** [comment]
I fixed most of the style issues present, but I'm not going to significantly touch `DeclinationHelper`, it's just too far gone. We'll integrate this once you confirm the licensing won't be an issue, but please have someone re-write this to be legible, and meet our style requirements.

**Comment by jlipschutz** [comment]
I will be sure to clean up this code during Wednesday's meeting. Thanks for helping.

**Comment by jlipschutz** [comment]
This is from the WMM website and 3rd party software page: 

Several users have ported the WMM C or Fortran programs to other languages and have kindly offered to share these programs. Neither the authors nor NGDC can provide any warranty or technical support for these programs. Only non-commercial "free-ware" will be linked to from this site. Linking to third party software does not imply an endorsement or review of any kind from the Federal Government. Users are encouraged to verify results based on the WMM test values. NOAA Disclaimer for external links. Many of these software still use WMM2010.

The WMM source code is in the public domain and not licensed or under copyright. The information and software may be used freely by the public. As required by 17 U.S.C. 403, third parties producing copyrighted works consisting predominantly of the material produced by U.S. government agencies must provide notice with such work(s) identifying the U.S. Government material incorporated and stating that such material is not subject to copyright protection.

**Comment by CaiB** [comment]
Alright, thanks.

I'd say this should be the priorities for updating this:
- Adding documentation, to help users understand how to use this utility. I added some basic info, but I'm not very familiar with how this works, so it's probably best to check/update what I wrote.
- Add instructions for how to update the data, so that people working on this in the future can easily update the model.
- Create unit tests to check that outputs are as expected. Obviously these will need to be updated if the model data updates.
- Add more comments to explain what the code is doing.
- Remove the redundant variables. There's no reason to have line 146, `double pi = Math.PI;`. Just use `Math.PI` directly.
- Rename variables to match style, and mean _something_. Names like `st`, `a`, etc. are completely useless.

For now, I vote to integrate so that this can be used, but please continue to work on this.

**Comment by jlipschutz** [comment]
Will definitely work on those priorities throughout this week. Thanks for the help!

**Pull request merged**
